# 1. Conexão com o PostgreSQL via Docker
spring.datasource.url=jdbc:postgresql://localhost:5432/costa_azul
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# 2. Configurações do Hibernate e JPA
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# REGRA DA EQUIPE: Apenas valida a estrutura, não tenta criar nem alterar as tabelas
spring.jpa.hibernate.ddl-auto=validate

# 3. Logs do Console (Opcional, mas excelente para debug)
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


#h2 Comentado
#spring.datasource.url=jdbc:h2:mem:costaazuldb
#spring.datasource.driverClassName=org.h2.Driver
#spring.datasource.username=sa
#spring.datasource.password=
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.jpa.hibernate.ddl-auto=update