spring.application.name=logincomercial

# Configuração do banco em memória H2
spring.datasource.url=jdbc:h2:mem:logincomercialdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Cria e atualiza as tabelas automaticamente baseado nas classes
spring.jpa.hibernate.ddl-auto=update

# Habilita o console do H2 no navegador
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console